---

# Configure apache

- name: Configure Apache
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: apache_ports_configuration_items
  notify: restart apache

- name: Add Apache vhosts
  template:
    src: "../templates/apache.conf.j2"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts
