---

# Install apache

- name: Install httpd
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-devel
    - mod_ssl
    - openssh
    - php

- name: Enable httpd service
  service: name=httpd state=started enabled=yes