---

libvirt_main_version: 1
libvirt_sub_version: 3
libvirt_chk_version: 1

libvirt_version: "{{ libvirt_main_version }}.{{ libvirt_sub_version }}.{{ libvirt_chk_version }}"

libvirt_download_page: "http://libvirt.org/sources/libvirt-{{ libvirt_version }}.tar.gz"

clean_after: true

libvirt_file: "libvirt-{{ libvirt_version }}.tar.gz"
libvirt_folder: "libvirt-{{ libvirt_version }}"
libvirt_tmp_folder: /tmp/libvirt/
libvirt_tmp_download_file: "{{ libvirt_tmp_folder }}/{{ libvirt_file }}"

libvirt_dependencies:
  - libxml2-devel
  - kvm
  - gnutls-devel
  - device-mapper-devel
  - libnl-devel
  - libpciaccess-devel
  - yajl-devel
  - xhtml1-dtds

libvirt_packages:
  - libvirt
  - libvirt-python
  - qemu-kvm
  - virt-manager
  - libguestfs-tools
  - libvirt-client
  - libvirt-daemon-kvm
  - libvirt-daemon
