---

- name: Create folder in /opt
  file: path={{ nodejs_folder }} state=directory

- name: Download nodejs
  get_url: url={{ nodejs_url_download }} dest={{ nodejs_folder }}

- name: Unzip the tarball
  command: tar xf {{ nodejs_tar_gz_file }} chdir={{ nodejs_folder }}

- name: Set nodejs PATH
  lineinfile: dest=/home/vagrant/.bashrc line="PATH={{ nodejs_folder }}{{nodejs_file_name}}/bin:$PATH" insertbefore="^export PATH"

- name: Reload bashrc
  shell: source /home/vagrant/.bashrc
  args:
    executable: /bin/bash